INSERT INTO MARCAS VALUES(1,'MERCEDES BENZ');
INSERT INTO MARCAS VALUES(2,'BMW');
INSERT INTO MARCAS VALUES(3,'CHEVROLET');
INSERT INTO MARCAS VALUES(4,'BRIDGESTON');
INSERT INTO MARCAS VALUES(5,'HONDA');
INSERT INTO MARCAS VALUES(6,'MICHELIN');
INSERT INTO MARCAS VALUES(7,'SCANIA');
INSERT INTO MARCAS VALUES(8,'FORD');
